apiVersion: camel.apache.org/v1
kind: KameletBinding
metadata:
  name: aws-ddb-streams-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: aws-ddb-streams-source
    properties:
      region: "The AWS Region"
      table: "The Table"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  