apiVersion: camel.apache.org/v1
kind: KameletBinding
metadata:
  name: aws-sns-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: aws-sns-sink
    properties:
      region: "The AWS Region"
      topicNameOrArn: "The Topic Name"
  