apiVersion: camel.apache.org/v1
kind: KameletBinding
metadata:
  name: azure-functions-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: azure-functions-sink
    properties:
      url: "https://azure-function-demo-12234.azurewebsites.net/api/httpexample"
  