apiVersion: camel.apache.org/v1
kind: KameletBinding
metadata:
  name: kafka-batch-apicurio-registry-not-secured-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: kafka-batch-apicurio-registry-not-secured-source
    properties:
      apicurioRegistryUrl: "The Apicurio Registry URL"
      bootstrapServers: "The Bootstrap Servers"
      topic: "The Topic Names"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  