apiVersion: camel.apache.org/v1
kind: KameletBinding
metadata:
  name: kafka-batch-azure-schema-registry-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: kafka-batch-azure-schema-registry-source
    properties:
      azureRegistryUrl: "The Azure Schema Registry URL"
      bootstrapServers: "The Bootstrap Servers"
      password: "The Password"
      topic: "The Topic Names"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  